### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by machinesmith42** [Xmader/musescore-downloader#1]

**Comment by Xmader** [comment]
fix in v0.1.7

**Comment by machinesmith42** [comment]
![image](https://user-images.githubusercontent.com/30908256/69892534-231db800-12cc-11ea-8c95-e67db74d366b.png)

**Comment by machinesmith42** [comment]
not working
asks for pro still

**Comment by machinesmith42** [comment]
v0.1.7 installed

**Comment by Xmader** [comment]
Did you enable it in a [user script manager](https://greasyfork.org/en/help/installing-user-scripts), like [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo)?
And what is your browser?

**Comment by machinesmith42** [comment]
tested in both chrome and firefox and use tamper monkey to install it

**Comment by machinesmith42** [comment]
also tested w greasemonkey

**Comment by Xmader** [comment]
So weird,
it works on the same page on my device, and in both Firefox and Chrome.
Can you open the Web Developer Console (press <kbd>Ctrl-Shift-I</kbd>, switch to `Console` tag), and copy something error to me?

![](https://user-images.githubusercontent.com/16057139/69892941-063bb180-12d9-11ea-9977-03c211d1dee2.png)

**Comment by machinesmith42** [comment]
Now works but on clicking download pdf get 404 error

**Comment by machinesmith42** [comment]
![image](https://user-images.githubusercontent.com/30908256/69893511-e35ccd80-12d7-11ea-8d9c-7a2e68321def.png)
![image](https://user-images.githubusercontent.com/30908256/69893517-fd96ab80-12d7-11ea-94a5-a59eaa58671c.png)

**Comment by Xmader** [comment]
Yes, I mentioned it in #2
