### ISSUE TITLE
Not working on firefox, apparently.

### ISSUE THREAD

**Issue by otaviomad** [Xmader/musescore-downloader#10]
No extra buttons are shown. Using FF 74.0 with greasemonkey.
![image](https://user-images.githubusercontent.com/6334573/77370949-d3627100-6d40-11ea-80c4-6bc3ad789325.png)

**Comment by otaviomad** [comment]
huh. it's working on brave with tampermonkey

**Comment by Ectalite** [comment]
It does work on firefox 74.0.1 with tampermonkey 4.10.6105
![image](https://user-images.githubusercontent.com/31344054/78547690-c6915300-77ff-11ea-8168-bbc5074afcae.png)

**Comment by Crotolamo** [comment]
Yup, not working on Firefox  GreaseMonkey  ver of scrip: 0.6.4
I'll try to use tampermonkey

**Comment by Crotolamo** [comment]
DONT use GreaseMonkey
Working perfectly on  Tamper Monkey, love you dev. :)

**Comment by Xmader** [comment]
The problems on Greasemonkey is now fixed in `v0.6.5`.
