### ISSUE TITLE
Download mscz failed using extension

### ISSUE THREAD

**Issue by misaka00251** [Xmader/musescore-downloader#101]
[Example](https://musescore.com/user/33272014/scores/6523220).

```
Error: score not in dataset
    at 6523220:26658
    at Generator.next (<anonymous>)
    at fulfilled (6523220:8)
```

**Comment by SkytAsul** [comment]
Another example of a more simple score: https://musescore.com/scores/from-the-king-eternal-monarch/if-only-881818441677784

**Comment by Xmader** [comment]
Report them in [![Discord](https://img.shields.io/discord/774491656643674122?color=7289da&label=Discord&logo=discord)](https://discord.gg/DKu7cUZ4XQ) [`#dataset-bugs `](https://discord.com/channels/774491656643674122/780520933101535232)

**Comment by philos2** [comment]
The extension does not work for this page 
https://musescore.com/scores/faure-gabriel/3-nocturnes-op33-524128962329414
Please if anyone can help.
Thank you very meuch
