### ISSUE TITLE
Button Blocks position

### ISSUE THREAD

**Issue by ClaudioAmato** [Xmader/musescore-downloader#102]
### You can add this block of code into the DIV for a better visualization:

**Add**
```
width: 422px !important; 
right: 0 !important; 
left: unset !important; 
margin: 0 18px 18px 0;
text-align: center;
```

**Remove**
```
flex-wrap: wrap;
display: flex;
```

**_AND_**

### As regards the @mediaquery when it changes the aspect of the page do this modification:
```
width: auto !important;
top: 1115px !important;
text-align: center;
left: unset !important; 
```

**Remove**
```
flex-wrap: wrap;
display: flex;
```

**Comment by Xmader** [comment]
Thanks. It will be released in `v0.23.0`.
