### ISSUE TITLE
CLI cannot seem to download this sheet properly 

### ISSUE THREAD

**Issue by Fenway17** [Xmader/musescore-downloader#105]
CLI cannot seem to download this sheet properly 
https://musescore.com/bluephoenixpiano/warriors-league-of-legends
it leads to a different sheet everytime, which i guess is related to these sheets having the same code?

**Comment by PeterNjeim** [comment]
Please uninstall any extensions you got from here. Instead, follow the instructions in the new repo, as this repo is no longer updated: https://github.com/LibreScore/dl-librescore
