### ISSUE TITLE
Web extension Button Layout Issue

### ISSUE THREAD

**Issue by CrashPlayer** [Xmader/musescore-downloader#108]
The Download Buttons in the web extension go out of the scrollview, when you scroll down. I can't conntribute myself since I don't know JavaScript, but it seems, that you set the buttons' position based on the scroll position of that field. Wouldn't it be simpler to just replace the HTML-Element of the Download-Button and replace it with yours?

**Comment by Xmader** [comment]
Initially it did what you said, but it can be detected very easily, so I changed it to a floating shadow element.
