### ISSUE TITLE
Score not in dataset

### ISSUE THREAD

**Issue by Kevin19281** [Xmader/musescore-downloader#109]
http://prntscr.com/102p8f0

**Comment by Tibec** [comment]
Getting the same error too

**Comment by Xmader** [comment]
https://github.com/Xmader/musescore-downloader/issues/101#issuecomment-767649847

**Comment by Xmader** [comment]
> http://prntscr.com/102p8f0

download using this link https://ipfs.io/ipfs/QmRH1k3kEumpMUdjeDaHJE6F9mAKMzqK7th7QAEknuTsqx?filename=6558218.mscz
