### ISSUE TITLE
Score not in dataset error with npx msdl command

### ISSUE THREAD

**Issue by Jasper-Nelligan** [Xmader/musescore-downloader#111]
Saw a previous closed issue about this but it still hasn't been fixed. This happened when I was trying to download https://musescore.com/user/3435661/scores/3470281 using the npx msdl command:

C:\Users\Jasper>npx msdl
npx: installed 58 in 100.409s
? Score URL or path to local MSCZ file:
  (starts with "https://(s.)musescore.com/" or local filepath ends with ".mscz") rig
  https://musescore.com/user/3435661/scores/3470281
Error: no such link found
    at C:\Users\Jasper\AppData\Roaming\npm-cache\_npx\6660\node_modules\msdl\node_mo
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Jasper\AppData\Roaming\npm-cache\_npx\6660\node_modules\m
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
! ID: 335327973726027
  Title: Pumped up kicks
  Continue? Yes

× score not in dataset
(node:6660) UnhandledPromiseRejectionWarning: Error: no such link found
    at C:\Users\Jasper\AppData\Roaming\npm-cache\_npx\6660\node_modules\msdl\node_mo
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Jasper\AppData\Roaming\npm-cache\_npx\6660\node_modules\m
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6660) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated ether by throwing inside of an async function without a catch block, or by rejecting a promise which has not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejection=strict` (see https://node.js.org/api/cli.html#cli_unhandled_rejections_mode). (rejecion id: 1)
(node:6660) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejection that are not handled will terminate the Node.js process with a non-zero exist code.

**Comment by reydus** [comment]
Can confirm I got the same issue with: https://musescore.com/user/5060686/scores/2260706

```
? Score URL or path to local MSCZ file:
  (starts with "https://(s.)musescore.com/" or local filepath ends with ".mscz") right-click to paste
  https://musescore.com/user/5060686/scores/2260706
! ID: 2260706
  Title: Disney Pixar&#039;s Up - Main Theme
  Continue? Yes

- Processing…(node:3348) UnhandledPromiseRejectionWarning: Error: no such link found
    at C:\Users\raymo\AppData\Roaming\npm-cache\_npx\3348\node_modules\msdl\node_modules\musescore-downloader\dist\cli.js:499:15
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\raymo\AppData\Roaming\npm-cache\_npx\3348\node_modules\msdl\node_modules\musescore-downloader\dist\cli.js:13:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:3348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3348) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
× score not in dataset
```

**Comment by SealsRock12** [comment]
Please post in #dataset-bugs in the discord server. All support is currently being provided in the Discord server.
