### ISSUE TITLE
Would it be possible to show more informative progress information?

### ISSUE THREAD

**Issue by Kyuuhachi** [Xmader/musescore-downloader#112]
Just showing "Processing..." for 20 seconds isn't very informative; showing some kind of progress information would be nice.

**Comment by PeterNjeim** [comment]
Please uninstall any extensions you got from here. Instead, use Tampermonkey and follow the instructions in the new repo, as this repo is no longer updated: https://github.com/LibreScore/dl-librescore

**Comment by Xmader** [comment]
Reopened as https://github.com/LibreScore/dl-librescore/issues/14

(I can't transfer issue across organizations)
