### ISSUE TITLE
Error downloading

### ISSUE THREAD

**Issue by elmundomusical4** [Xmader/musescore-downloader#115]
Hi. With some scores, like this, I get an error when I try to download it. Here is the score: https://musescore.com/user/29306356/scores/5270875#
Thanks!

**Comment by SealsRock12** [comment]
Hello, all support is currently being provided in the discord server:
[![Discord](https://camo.githubusercontent.com/9e80098444f69aca9ee4a7f3b0352f95f20a628b0c37c8afc077d47044e580f6/68747470733a2f2f696d672e736869656c64732e696f2f646973636f72642f3737343439313635363634333637343132323f636f6c6f723d373238396461266c6162656c3d446973636f7264266c6f676f3d646973636f7264)](https://discord.gg/DKu7cUZ4XQ) 

This is probably a dataset bug, you need to post it in the #dataset-bugs channel there.
