### ISSUE TITLE
What a great program! But it seems that the Individual part can't be down loaded now...

### ISSUE THREAD

**Issue by WKL0423** [Xmader/musescore-downloader#117]
I'm using it on edge and The main PDF&MP3's downloading still works but the XML and individual parts are always just progressing and nothing happens then... Please fix it! Appreciate! This program really helps!

**Comment by DereC4** [comment]
Same

**Comment by PeterNjeim** [comment]
@DereC4 this repo is not updated anymore. Please use the new repo: https://github.com/LibreScore/dl-librescore. To download "individual parts" (pdf for separate parts), use the LibreScore app to download MSCZ, then use the Webmscore website to convert it to PDF parts. All details are in the linked GitHub page
