### ISSUE TITLE
Issue with downloading mp3 and midi

### ISSUE THREAD

**Issue by MrSkullium** [Xmader/musescore-downloader#118]
Whenever I go to a song and try to press either of those two buttons, it just refuses to show the download prompt on my device. If you know how to fix this, thanks. (I'm using the firefox addon for pc)

**Comment by PeterNjeim** [comment]
Do not use the Firefox Add-on, use either the Tampermonkey script or the CLI method. The Firefox and Chrome extensions are not always up-to-date. Follow the instructions for the Userscript section in the readme and uninstall the Firefox Add-on
