### ISSUE TITLE
Not working for most of the Musescore files (nor PDf not Midi)

### ISSUE THREAD

**Issue by SMLibrary** [Xmader/musescore-downloader#119]
Not working for most of the Musescore files (not PDf nor Midi).
For instance:
https://musescore.com/classicman/chopin-opus-28-no-4
https://musescore.com/user/122383/scores/169484
https://musescore.com/fakeyourdeath/schubert-impromptu-no-2-in-e-flat-major-op-90
https://musescore.com/fakeyourdeath/toccata-and-fugue-in-d-minor-bwv-565-johann-sebastian-bach-bach-toccata-and-fugue-in-d-minor-bwv-595-piano-version
https://musescore.com/fakeyourdeath/mozart-rondo-alla-turca-metal-version/piano-tutorial

However, it seems to work with some others.
Thank you!

**Comment by SealsRock12** [comment]
Hello, all technical support is currently being provided in the discord server:
[![Discord](https://camo.githubusercontent.com/9e80098444f69aca9ee4a7f3b0352f95f20a628b0c37c8afc077d47044e580f6/68747470733a2f2f696d672e736869656c64732e696f2f646973636f72642f3737343439313635363634333637343132323f636f6c6f723d373238396461266c6162656c3d446973636f7264266c6f676f3d646973636f7264)](https://discord.gg/DKu7cUZ4XQ) 

This is probably a dataset bug, you need to post it in the #dataset-bugs channel there.

**Comment by PeterNjeim** [comment]
> Weirdly, all scores of these work for me with MIDI and PDF download. Is your script up-to-date?

They said that the musescore files weren't working, and specifically not the pdf and midi files. That means they aren't in the dataset, but you just added them so it'll all be fixed tomorrow. With the latest update to the tampermonkey script, it will notify the user to send the url to the #dataset-bugs channel in the discord server, and hopefully these issues on github won't appear anymore.
