### ISSUE TITLE
Download Buttons disappeared.

### ISSUE THREAD

**Issue by noonononnonnoo** [Xmader/musescore-downloader#124]
The download buttons that are usually found at the top right of the page to download the files just aren't appearing for me.

**Comment by SealsRock12** [comment]
Hello, all technical support is currently being provided in the discord server:
[![Discord](https://camo.githubusercontent.com/9e80098444f69aca9ee4a7f3b0352f95f20a628b0c37c8afc077d47044e580f6/68747470733a2f2f696d672e736869656c64732e696f2f646973636f72642f3737343439313635363634333637343132323f636f6c6f723d373238396461266c6162656c3d446973636f7264266c6f676f3d646973636f7264)](https://discord.gg/DKu7cUZ4XQ)
