### ISSUE TITLE
[REQUEST]Firefox android add-on support

### ISSUE THREAD

**Issue by KyleBroflowski** [Xmader/musescore-downloader#127]
It would be great to have this among the already limited  android compatible  add-onz of firefox

**Comment by Xmader** [comment]
The extension itself supports Firefox Android.
However, [only selected recommended extensions can be installed directly from addons.mozilla.org (AMO)](https://blog.mozilla.org/addons/2021/01/20/extensions-in-firefox-for-android-update/).
