### ISSUE TITLE
I can't download some mscz. It says failed download. For example, this one. https://musescore.com/irelin/salut-d-amour-for-cello-piano     

### ISSUE THREAD

**Issue by mtl73** [Xmader/musescore-downloader#128]

**Comment by SealsRock12** [comment]
Hello, all technical support is currently being provided in the discord server:
[![Discord](https://camo.githubusercontent.com/9e80098444f69aca9ee4a7f3b0352f95f20a628b0c37c8afc077d47044e580f6/68747470733a2f2f696d672e736869656c64732e696f2f646973636f72642f3737343439313635363634333637343132323f636f6c6f723d373238396461266c6162656c3d446973636f7264266c6f676f3d646973636f7264)](https://discord.gg/DKu7cUZ4XQ)

**Comment by Xmader** [comment]
already fixed
