### ISSUE TITLE
Unreadable file.

### ISSUE THREAD

**Issue by filipporomani** [Xmader/musescore-downloader#131]
Hi, 
Each time I download a score in the MSCZ format the Musescore software says that the file is not readable. Each time i must download files in pdf and then convert them to MSCZ, is there any kind of fix?
I'm using the latest version of the software and of the script. Any solution?

**Comment by mical385** [comment]
can u try again and take a pic?

**Comment by filipporomani** [comment]
Problem sloved, it was a download problem
