### ISSUE TITLE
Can't seem to download a Score except for the PDF.

### ISSUE THREAD

**Issue by IamRifki** [Xmader/musescore-downloader#136]
Tried downloading this score https://musescore.com/user/36087419/scores/6861180, but it seems like it can't download it aside form the PDF.

**Comment by PeterNjeim** [comment]
Please uninstall any extensions you got from here. Instead, use Tampermonkey and follow the instructions in the new repo, as this repo is no longer updated: https://github.com/LibreScore/dl-librescore
