### ISSUE TITLE
globalThis is not defined

### ISSUE THREAD

**Issue by likeablePanda** [Xmader/musescore-downloader#139]
I followed the instructions directly on my linux machine, ubuntu 20.04, and got the following message after executing npx msdl

```
$npx msdl
npx: installed 61 in 3.816s
globalThis is not defined

```

Version checks:
```
$npm --version
6.14.15
$npx --version
6.14.15
```

**Comment by Xmader** [comment]
The minimum required Node.js version is [12](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#browser_compatibility). Make sure you've upgraded it.

**Comment by likeablePanda** [comment]
> Node.js is version 12

npm version 6.14.15  is what's in node.js LTS, 14.18.0 @Xmader 

At least according to https://nodejs.org/en/download/

**Comment by likeablePanda** [comment]
I figured it out.

Turns out there was two Node.js on my computer for some reason. I used sudo apt remove to remove the older one.

The new one was "node" the old version was called "nodejs"

So i ran
sudo apt remove nodejs

and then it defaulted to the newer "node" command behind the scenes.
