### ISSUE TITLE
Midi downloads dont download the entire midi

### ISSUE THREAD

**Issue by angurishu** [Xmader/musescore-downloader#140]
Just for some clarification; I am fully able to download the midi file completely with no issues from my browser using the script, however, when I import the file into my daw, inside the midi file the score seems to be only half of what was shown on the website itself. As in it would download the chords or even the bass line but not the melodies of the singer and whatnot - is there a fix for this?

It happens to most files, but in some cases the midi files show the complete notes so I don't know what's going on

**Comment by poudink** [comment]
If I remember correctly, that is Musescore's fault rather than the extension, as I often had similar issues (most notably with Anvil Studio) back when download was free. To get around it, I used a program (don't remember which, but it shouldn't be too difficult to find one) that did not have issues with Musescore's MIDIs and re-exported them, which would then get them working just fine.

**Comment by PeterNjeim** [comment]
@angurishu are you using FL Studio? Please don't say "my daw" as it gives no useful information. If you're using FL Studio, make sure you aren't simply opening the MIDI file from File Explorer, and instead use `File > Import > MIDI file` from FL Studio.

**Comment by PeterNjeim** [comment]
Also, this repo is not updated anymore. Please use the new repo: https://github.com/LibreScore/dl-librescore.

**Comment by angurishu** [comment]
> Also, this repo is not updated anymore. Please use the new repo: https://github.com/LibreScore/dl-librescore.

@PeterNjeim Sorry about that! But yeah I do use FL Studio and I tried importing midi the way you said so by importing using the file option however it still doesn't have all the midi data unfortunately. I used ableton and it imports things properly in multiple midi files but FL Studio has only one midi file, usually the lower bass notes. Is there any other way to counteract this?

**Comment by PeterNjeim** [comment]
Your usage of the word "file" is a little wrong, you probably mean "channel". FL Studio by default should import all MIDI tracks into separate channels, make sure this option is checked when importing. Also make sure that the "All tracks" option is selected for the "Which tracks to import?" option. If it still doesn't work you can send me the URL of your song and I can determine the problem myself

**Comment by Xmader** [comment]
The script downloads midi files [directly from musescore.com's server](https://github.com/LibreScore/dl-librescore/blob/4fe9084/src/file.ts#L10-L12). We couldn't help with anything sorry.
