### ISSUE TITLE
mscz download doesn't work anymore...

### ISSUE THREAD

**Issue by Kyridiculous2** [Xmader/musescore-downloader#141]
Is there any plan to fix it?

**Comment by CSharperMantle** [comment]
Perhaps you would like to see the new [LibreScore/app-librescore](https://github.com/LibreScore/app-librescore)?

Also, joining the discord channel (at #68) helps!

**Comment by Galang23** [comment]
2022 and still not working

**Comment by guysoft** [comment]
Hey, the discord url is invalid, there there a new one @CSharperMantle ?

**Comment by CSharperMantle** [comment]
@guysoft I am not a admin of the discord Haha. The url is taken from #68. You may wish to check there if there's any updates.

**Comment by guysoft** [comment]
Ok the url there works! Thanks!
ill post there later

**Comment by PeterNjeim** [comment]
@Kyridiculous2 @Galang23 new repo is hosted here: https://github.com/LibreScore/dl-librescore

**Comment by Xmader** [comment]
mscz download could be added back to the script (under the [new repo](https://github.com/LibreScore/dl-librescore)) in the future, but not planned right now.
