### ISSUE TITLE
Extension is disabled

### ISSUE THREAD

**Issue by DereC4** [Xmader/musescore-downloader#143]
The extension is disabled on my browser with the message "This extension is not listed in the Web Store and may have been added without your knowledge. Learn more"

**Comment by rphlmnbt** [comment]
I just turned the extension on again manually and its working again. There is a toggle on chromes extension pages.

**Comment by PeterNjeim** [comment]
Please uninstall any extensions you got from here. Instead, use Tampermonkey and follow the instructions in the new repo, as this repo is no longer updated: https://github.com/LibreScore/dl-librescore

**Comment by Xmader** [comment]
Extension support could be added back in the future, in the [new repo](https://github.com/LibreScore/dl-librescore).

**Comment by DereC4** [comment]
This was 2, 3, no FOUR (wtf it's been that long!) years ago😭 i found my own fixes oops but thanks for updating
