### ISSUE TITLE
incorrect file extension output for express download midi files

### ISSUE THREAD

**Issue by Arthursza** [Xmader/musescore-downloader#147]
express download is currently saving .mid files as .midi, that not a issue to anyone that is aware, but some workstations didnt read .midi files, only the 3 digit .mid. i  know its a very insignifcant issue but anyway...

**Comment by Xmader** [comment]
`.mid` and `.midi` are both [valid extension names](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types) for midi files.
You could rename the file anyways.
