### ISSUE TITLE
Is it possible to download individual parts?

### ISSUE THREAD

**Issue by Samda1** [Xmader/musescore-downloader#15]
First of all, thanks so much for making this.

Is it possible to download individual parts of a score instead of the entire score?

**Comment by Xmader** [comment]
Sorry, I can't find such an API to do it without Musescore Pro.

You can download the [Musescore software](https://musescore.org/en), and do it manually in the software.

Maybe I can implement it in my new [LibreScore](https://github.com/LibreScore) project.

**Comment by Xmader** [comment]
The ability to download individual parts is now included in the version `v0.7.0`, with the power of LibreScore's [webmscore](https://github.com/LibreScore/webmscore).

Just click the `Download Parts` button, and choose which part to download.

**Comment by Encritary** [comment]
What about downloading parts as MIDI?
