### ISSUE TITLE
emmmm

### ISSUE THREAD

**Issue by molihuaacha** [Xmader/musescore-downloader#150]
i cant download MSCZ

**Comment by PeterNjeim** [comment]
Please uninstall any extensions you got from here. Instead, use Tampermonkey and follow the instructions in the new repo, as this repo is no longer updated: https://github.com/LibreScore/dl-librescore

**Comment by PeterNjeim** [comment]
Please uninstall any extensions you got from here. Instead, follow the instructions in the new repo, as this repo is no longer updated: https://github.com/LibreScore/dl-librescore
