### ISSUE TITLE
I get this error and nothing goes after this.

### ISSUE THREAD

**Issue by CongoBB** [Xmader/musescore-downloader#152]
![image](https://user-images.githubusercontent.com/36362414/180641262-29e2adb7-db85-4a69-820c-037d77ba8bfb.png)

**Comment by CongoBB** [comment]
Could you please help? :)

**Comment by SealsRock12** [comment]
This is an old version. You can find the new version [here](https://github.com/LibreScore/dl-librescore).

**Comment by Xmader** [comment]
The code that caused the error is still [there in the new repo](https://github.com/LibreScore/dl-librescore/blob/2d1d5ba/src/scoreinfo.ts#L111).
I don't know if it's indeed fixed.
