### ISSUE TITLE
Italian translation is wrong

### ISSUE THREAD

**Issue by CoderLel** [Xmader/musescore-downloader#156]
Italian translations has lots of errors, often completely changing the sentences. Documentation is important, and there are quite a few sentences whitout meaning.
How can I help? Thanks

**Comment by sealsrock12** [comment]
This repo is not being used anymore. The new repo is [here](https://github.com/LibreScore/dl-librescore). It also has a better system for translations

**Comment by PeterNjeim** [comment]
You can help translate our new projects and documentation here: https://weblate.librescore.org/
