### ISSUE TITLE
Downloading a MSCZ fails, but a MXL or pdf works

### ISSUE THREAD

**Issue by Rotekoppen** [Xmader/musescore-downloader#19]
Please tell me where i can find logs if you want them.

Firefox 77.0.1
Script ver  0.7.1
Tampermonkey v 4.11.6114

**Comment by Xmader** [comment]
<kbd>F12</kbd> - `Network` - search `mscz`

**Comment by Weirdguyz** [comment]
Not the original person but getting the same error, going into the network tab shows that the request yields a 404. Don't know exactly what you need to see so various screenshots are below of what I see. What's odd though is that while the original poster had the issue two weeks ago, I was fine up until today.
![image](https://user-images.githubusercontent.com/40163448/86526712-82811d80-bed6-11ea-99d4-25959521ef2c.png)
![image](https://user-images.githubusercontent.com/40163448/86526717-8f9e0c80-bed6-11ea-87cd-a85e37986a42.png)

**Comment by Xmader** [comment]
This was an attempt to take down musescore-downloader. Someone contacted `now.sh` (now `vercel.com`), and they disabled my deployment.

**Comment by Xmader** [comment]
By the way, this repo has been moved to https://github.com/LibreScore/dl-librescore
