### ISSUE TITLE
Musescore API changed

### ISSUE THREAD

**Issue by Xmader** [Xmader/musescore-downloader#2]
**The fxxxing Musescore Company** may know the existence of this script or something like this.

They changed the download URL to `mscz` and `pdf` file, 
from (for example [sheet music id 5850193](https://musescore.com/classicman/scores/5850193) )
```
https://musescore.com/static/musescore/scoredata/score/3/9/1/5850193/score_9752393_f902a13ed340103c3810b7e6bb10124087cacde6.mscz
```
, to direct AWS S3 urls (**with `X-Amz-Credentiall` `X-Amz-Signature` params that only came from the API server, this script can't get them directly**)
```
https://s3.ultimate-guitar.com/musescore.scoredata/score/3/9/1/5850193/score_9752393_f902a13ed340103c3810b7e6bb10124087cacde6.mscz?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential={}&X-Amz-Date={}&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Signature={}
```

**So `Download Musescore` and `Download PDF` buttons are now not working.**

I'll try my best to solve it.

**Comment by machinesmith42** [comment]
Will this be fixable?

**Comment by machinesmith42** [comment]
It is possible to pull svgs of the sheet music

**Comment by Xmader** [comment]
fix `Download Musescore` button in `v0.2.0`

**Comment by Xmader** [comment]
fix `Download PDF` button in v0.3.0

**Comment by Xmader** [comment]
> 
> 
> It is possible to pull svgs of the sheet music

Thank you, I use svgs to generate PDF

**Comment by cy-polo** [comment]
Hey @Xmader, I think one of the best things that will always work is to use `scoredata` data to regenerate a PDF, a musicxml file, an MSCZ file, without needing to have the pro version.

It's an idea I wanted to make. If the musicxml file is recreated, we can do anything.

![image](https://github.com/Xmader/musescore-downloader/assets/50364607/96ba8cae-b743-46fd-8041-ac6c9ddef61d)
