### ISSUE TITLE
Not an issue, but would you be able to provide api docs?

### ISSUE THREAD

**Issue by fishjojo1** [Xmader/musescore-downloader#20]
Hi, this isn't an issue per se, but, do you still have, and would you be able to provide musescore's api documentation?
Or rather, what url and parameters are used in downloading the files? (pdf, mszc etc)
Lastly, thanks for your contributions to the community really agree with your ideals that these scores should not be paid unless the transcriber wants it to be so.

**Comment by chiragzq** [comment]
They took down the API docs after this repository gained some traction, however it is archived at https://web.archive.org/web/20200117065437/https://developers.musescore.com/ :)

**Comment by magnus-gross** [comment]
They did not only take down the API docs, but the API itself, so the docs above won't help you much.

I think he is asking for docs for the unofficial API.
