### ISSUE TITLE
Convert as web extension

### ISSUE THREAD

**Issue by Mte90** [Xmader/musescore-downloader#21]
It is possible to convert it as web extension?
In this way I don't need greasemonkey just for this script?

**Comment by dayoshiguy** [comment]
this!

**Comment by Xmader** [comment]
landed in `v0.10.0`

**Comment by Mte90** [comment]
BUt is not published yet on addons.firefox and Chrome Webstore right?

**Comment by Xmader** [comment]
The extensions are pending reviewing by someone on those sites. It may take days.

**Comment by Xmader** [comment]
The extension on addons.mozilla.org is [up](https://addons.mozilla.org/en-US/firefox/addon/musescore-downloader/).

**Comment by Mte90** [comment]
![Screenshot_2020-11-06](https://user-images.githubusercontent.com/403283/98350123-32000500-201b-11eb-8b81-b3b815395dd0.png)
Seems that musescore can detect that extension :-(

**Comment by Xmader** [comment]
fixed in `v0.11.4`

**Comment by Mte90** [comment]
Confirmed now is working :-D
