### ISSUE TITLE
MSCZ file issue

### ISSUE THREAD

**Issue by HmLeoM** [Xmader/musescore-downloader#23]
Hey there, I'm having a lil issue at opening MSCZ files, the thing is I can download em without problems tho, but when I try to open it, it shows me the next issue
![image](https://user-images.githubusercontent.com/70286038/91338194-90e70980-e7a2-11ea-9c3c-96375f4ca5b5.png)

And yes, my musescore is at the last version... What would be the issue?

**Comment by GavinWoodward** [comment]
I have been having to deal with the same issue. At this point I have exhausted all attempts to fix it on my own. It cannot possibly be a genuine update message as it would never appear as a score and instead would appear as some kind of window. While I would assume it to be unlikely, this could be the result of some kind of attack on the script.

**Comment by Frikderbaumkuchen** [comment]
A temporary fix is just to download the .mxl file. It works just like the MSCZ file for me and you can open it as mxl and save it as MSCZ if you really need it.

**Comment by Xmader** [comment]
MuseScore has changed their API.

**Comment by emerson-code** [comment]
same goes with me, hoping that it will be fixed, thanks xmader , not all heroes wear cape, and ur one of them XD

**Comment by johnpotato1109** [comment]
> A temporary fix is just to download the .mxl file. It works just like the MSCZ file for me and you can open it as mxl and save it as MSCZ if you really need it.

Thank you. It really works now!!!

**Comment by Xmader** [comment]
I just released a [temporary fix](https://github.com/Xmader/musescore-downloader/commit/9ec77865f0617e423bb93c47f42bfaa08eb740fc). 
The script will use mscz files from my [dataset](https://github.com/Xmader/musescore-dataset#all-mscz-files). No new score after Aug 27 2020 can be downloaded for now, and the files may not be up-to-date.

Solutions for me to work on:
* Get a Pro account, and save mscz files to my dataset continuously, or
* Investigate the new API

Known info about the new API:
* The new API returns encrypted `mscze` files
* Each encrypted `mscze` file is larger than the original `mscz` file by 20 bytes
* Each `mscze` file has a 4-byte file header `XTZ\0` (`58 54 5a 00`), and a 16-byte encryption info header

(Not sure)
* The encrypted data is after the 20-byte header of a `mscze` file, using the 8-round [ChaCha20 encryption algorithm](https://en.wikipedia.org/wiki/Salsa20#ChaCha_variant)?
* [The `Nonce`](https://www.google.com/search?q=ChaCha20+Nonce) is the 8 byte data just after the `XTZ\0` header?
* The algorithm to calculate the key is unknown.

**Comment by Xmader** [comment]
BTW, the MuseScore mobile app uses code (for score file processing and audio synthesizing) from [the MuseScore desktop software](https://github.com/musescore/MuseScore), which is open source under [GPL](https://en.wikipedia.org/wiki/GNU_General_Public_License). Therefore, the MuseScore team (or UltimateGuitar, or [wsmgroup.ru](https://www.linkedin.com/company/wsm-group) actually) **must open source it** under the same licence as per the requirements of GPL.

**Comment by LoveJessyChen** [comment]
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: musescore/mscz/6338381.mscz</Details></Error>

**Comment by chopin2712** [comment]
Yes I have the same thing. But the MIDI output works tho.

**Comment by LoveJessyChen** [comment]
> Yes I have the same thing. But the MIDI output works tho. In my case, only MIDI and MP3 is working. 
> 
> 
> 
> * The MusicXML is rendering a 404
> 
> * The PDF is loading forever
> 
> * The MSCZ is `NoSuchKey`
> 
> * The "Individual parts" is just opening a tab where it's written "Processing..." then it ask me if I want to download the whole score in PDF. I do it and it gives me a blank PDF.

Yes，I have your same problems.

**Comment by LoveJessyChen** [comment]
Yes ，I have your same problems.

**Comment by Xmader** [comment]
Cracking Completed! (It shouldn't take so long)

**Comment by emerson-code** [comment]
Thanks

**Comment by mykolasolodukha** [comment]
@Xmader did you figure out how to decrypt the `mscze` files? I'm about to take it from there

**Comment by csa8820** [comment]
@Xmader did you figure out how to decrypt the mscze files? I'm about to take it from there
