### ISSUE TITLE
MusicXML - Not found error?

### ISSUE THREAD

**Issue by kolt54321** [Xmader/musescore-downloader#24]
Hi! I'm hitting 404 not found errors on most MusicXML downloads. Any idea why?

**Comment by Xmader** [comment]
The company that runs MuseScore goes crazy, and closed every potential way they think a score file could be downloaded without a Pro account.

**Comment by kolt54321** [comment]
Oh no! I've heard similar, but it's crazy that they try to shut off users
downloading royalty free music. Don't let it get to you! We appreciate all
that you do.

**Comment by richidubey** [comment]
Yeah, Keep up the good work!
