### ISSUE TITLE
Downloaded PDF unable to be zoomed out to be viewed in full on a tablet

### ISSUE THREAD

**Issue by Fenway17** [Xmader/musescore-downloader#26]
Oddly enough when PDF is downloaded using musescore downloader it is able to be viewed fully zoomed out mostly everywhere, PC or laptop, but on my Samsung tablet, its default view is a zoomed in state that doesnt allow me to zoom out, only in, preventing me from viewing the PDF in full zoomed out view.
Tested with PDFs that were downloaded before the dreaded musescore subscription changes and they can be viewed fully zoomed out as per normal, which leads me to think the musescore downloader formats the PDF differently.

![photo_2020-09-25_00-58-03](https://user-images.githubusercontent.com/24566006/94176095-2ec91380-feca-11ea-93a0-2f59bb09c2ae.jpg)

**Comment by Xmader** [comment]
Yes, the script formats the PDF differently if you download PDF files from the `Download PDF` button. It simply put sheet images shown on the page together into a PDF file. 

Consider using the `Individual Parts` button, and choose `Full score`. It generates PDF file from the MSCZ file (like you export PDF in MuseScore software).
