### ISSUE TITLE
export to musescore

### ISSUE THREAD

**Issue by machinesmith42** [Xmader/musescore-downloader#3]
Is this possible

**Comment by Xmader** [comment]
Do you mean open the sheet music directly in the Musescore software, 
or just want to download the `mscz` file (the first button can already do it)?

**Comment by machinesmith42** [comment]
First option

**Comment by PeterNjeim** [comment]
> First option

lol this is very late but to open in Musescore you just need to download the MSCZ file and open it in Musescore
