### ISSUE TITLE
Download MP3 not including all parts

### ISSUE THREAD

**Issue by North-West-Wind** [Xmader/musescore-downloader#30]
I tried downloading the MP3 of a sheetmusic with 40 parts, but the downloaded MP3 file have some parts missing. [Here is the link](https://musescore.com/xiaomigros/best-rainbow-road)

First, listen to the music played on Musescore. Then listen to the music downloaded. You will notice the melody missing for the downloaded file.

**Comment by Xmader** [comment]
The page actually plays [a YouTube video](https://www.youtube.com/watch?v=66C-E5sKEQs) in the background.

**Comment by North-West-Wind** [comment]
wow i never thought of that

**Comment by Xmader** [comment]
Open web developer tools using <kbd>F12</kbd>,  and search for `youtube`

**Comment by North-West-Wind** [comment]
It seems the iframe only appears after playing it. So we cannot use cheerio on this?

Also, I just realize the missing part is the error of Musescore itself, not the mp3.
