### ISSUE TITLE
Doesn't seem to work on firefox anymore?

### ISSUE THREAD

**Issue by MisterPapagiorgio** [Xmader/musescore-downloader#31]
I'm using the script with Violent Monkey, and it has worked in the past.  However, after I click the download button, I get the usual options (pdf, musecore, etc).  I click pdf, and instead of downloading, I get the window wanting me to subscribe.  Any tips?

![1](https://user-images.githubusercontent.com/72639393/95644816-34585900-0a87-11eb-8b16-08d4ff5979e5.jpg)

**Comment by sguillia** [comment]
Just tried on Chromium with Tampermonkey, it works fine.  
I don't know for Firefox but at least you can still download scores

**Comment by MisterPapagiorgio** [comment]
OK, I'll give Tampermonkey a try.  Thanks.
