### ISSUE TITLE
Download Keeps Failing

### ISSUE THREAD

**Issue by Endcrafter16** [Xmader/musescore-downloader#33]
The **MCSC** Download works **fine**

![bug repor 2](https://user-images.githubusercontent.com/57860862/96399516-1b774280-1201-11eb-8507-15e7b721ff0c.JPG)

But when downloading by pressing midi, mp3 and the other file formats it keeps on failing

![bug report](https://user-images.githubusercontent.com/57860862/96399586-43ff3c80-1201-11eb-9895-f25aeb067fa2.JPG)

**Comment by Xmader** [comment]
It seems to be a problem of musescore.com itself. Can all sheet images on that page load correctly?

**Comment by Peanut84** [comment]
> It seems to be a problem of musescore.com itself. Can all sheet images on that page load correctly?

Now that you mention no, they not loading properly

**Comment by Xmader** [comment]
fixed in ` v0.8.4`
