### ISSUE TITLE
Downloade Failed!

### ISSUE THREAD

**Issue by Peanut84** [Xmader/musescore-downloader#34]
First of all, ty so much for the script.
I have a problem, past release i had the 404 error when attempt to download Midi or mp3. Now with the update i have "Download Failed!" error when i try to download a midi or mp3.
![error](https://user-images.githubusercontent.com/73091226/96399765-8abf4900-11a5-11eb-9cc5-cbce7f168573.png)

**Comment by Xmader** [comment]
duplicated with #33
