### ISSUE TITLE
Doesn't let me download

### ISSUE THREAD

**Issue by Muhammadin96** [Xmader/musescore-downloader#35]
I tried to download a midi but it doesn't work anymore. It gives me a download failed warning.
![Capture](https://user-images.githubusercontent.com/73223725/96698263-7ce51000-13bf-11eb-8466-1cf78c978604.PNG)

please help.

**Comment by rtg11** [comment]
me too

**Comment by Xmader** [comment]
fixed in `v0.9.1`

**Comment by examateur** [comment]
Thanks a lot Xmader !
