### ISSUE TITLE
Can't download midi

### ISSUE THREAD

**Issue by okajimaitsuki** [Xmader/musescore-downloader#36]
I can't download midi file.
when I press button,text changed into "processing" but doesn't start downloading.
I've tried Google Chrome and Microsoft Edge with Ubuntu 20.10

**Comment by rtg11** [comment]
me too

**Comment by Chosaint** [comment]
I also am having this issue, I use Chrome browser usually, I installed Firefox thinking maybe it was a browser issue. Still just get "processing".
I've tried restarting the script, reinstalling the Tampermonkey and Musescore-Downloader, but it does not remedy the issue.
![MuseScoreDownloader](https://user-images.githubusercontent.com/35324014/96915616-4ceb4a80-145b-11eb-8e63-f0b5ae26eaa9.jpg)

**Comment by Xmader** [comment]
fixed in ` v0.9.2`

Note: 
`Download PDF` and `Download MIDI` has been deprecated (may still work). 
Use `Download PDF` or `Download MIDI` button inside `Individual Parts` instead.
