### ISSUE TITLE
0.9.2 update issues

### ISSUE THREAD

**Issue by Chosaint** [Xmader/musescore-downloader#37]
I was able to download one midi and it gave me an error saying it was "Deprecated" and to try to download from individual parts. I tried this with the other one I attempted to download and I am still unable to download the midi through individual parts. I tried using Chrome browser. I will retry with Firefox

![MuseScoreDownloader](https://user-images.githubusercontent.com/35324014/96934408-00ae0380-1477-11eb-8d12-6636c152456b.jpg)

Tried again with Firefox, and got the same issue, but was able to download it. Also closed and reopened Chrome and tried again with the same link and it gave the "deprecated" error but still downloaded the .midi
![FireFoxMusescoreDownloader](https://user-images.githubusercontent.com/35324014/96934693-82059600-1477-11eb-9304-756aa22f93e1.jpg)

**Comment by Xmader** [comment]
What's wrong with `Individual Parts`?

**Comment by Xmader** [comment]
Just click `OK`, and it will proceed to download.

**Comment by Chosaint** [comment]
Yes, my apologies it still works. It seemed it was just a one time hiccup, I've not had an issue since after clicking okay.
