### ISSUE TITLE
No Download buttons

### ISSUE THREAD

**Issue by asusplayer** [Xmader/musescore-downloader#38]
Hey, I just tried to download something but then I realized, that the Download - Buttons are not avaiable. I think musescore has changed some sourcecode so the plugin wont show up anymore, because it can't find the code. 
![image](https://user-images.githubusercontent.com/51540487/97004071-c313ae00-153c-11eb-8787-56656452f6ea.png)
also in chrome:
![image](https://user-images.githubusercontent.com/51540487/97004137-dde62280-153c-11eb-950e-e85ba515c4f5.png)
Thanks for help

**Comment by BenHilling03** [comment]
I got the same issue too.

**Comment by jacobvenborg** [comment]
Yep, me as well. Tried both FF and Chrome (both latest versions, I reckon) on Windows 10 using both ViolentMonkey and Tampermonkey. I've been succesfully using this script a few weeks earlier :) And thank you so much for this script, Xmader!

**Comment by mmikosu** [comment]
Same with me. I'm using Firefox Developer Edition 83.0b2, ViolentMonkey v2.12.7, and Windows 10 Build 19041.572.

**Comment by Xmader** [comment]
Wait one moment

**Comment by asusplayer** [comment]
Thank you!!

**Comment by BenHilling03** [comment]
Even after the update it still didnt work

**Comment by asusplayer** [comment]
It works on Firefox now! <3 Still nothing on Chrome

**Comment by Neiko-Real** [comment]
please chrome fix

**Comment by Neiko-Real** [comment]
new update, is it updating on greasyfork now?

**Comment by Neiko-Real** [comment]
FIXED, 0.9.3 duplicate name in greasyfork

**Comment by Xmader** [comment]
> FIXED, 0.9.3 duplicate name in greasyfork

I just made some mistakes. It should show `v0.9.4` now.

**Comment by Neiko-Real** [comment]
yes fixed thank you
