### ISSUE TITLE
Low quality for SVG scores

### ISSUE THREAD

**Issue by generalbrus** [Xmader/musescore-downloader#4]
Hi,
Thanks for working on this script!

I've noticed that downloading SVG scores results in low quality PDFs since you always convert a page to PNG before adding it to the PDF.

Not sure if you've looked into this already, but you can convert from SVG to PDF directly using [alafr/SVG-to-PDFKit](https://github.com/alafr/SVG-to-PDFKit).

I have forked version 0.4 of your code and applied the fix there (I am not too familiar with workers and I have't looked into yours). You can find my code here: https://github.com/generalbrus/musescore-downloader-hd

I did not make a PR since I worked on an older version.

**Comment by Xmader** [comment]
Thank you for your great work,
and thank you for letting me know the great `SVG-to-PDFKit`!

The script is now using `SVG-to-PDFKit` to convert SVG to PDF directly in version 0.5.0.
