### ISSUE TITLE
Is there a way to download this from musecore?

### ISSUE THREAD

**Issue by Kineo-Dev** [Xmader/musescore-downloader#40]
https://musescore.com/pro/landing/official-score?official_score_id=477334&feature=official-from-search-real

**Comment by TheAlienDrew** [comment]
See my pull https://github.com/Xmader/musescore-downloader/pull/49... the script works again, but must wait 8 seconds at the least so far for it to work again without tripping Musescore.

**Comment by Xmader** [comment]
The [updated version here](https://github.com/LibreScore/dl-librescore) should be able to download official scores.
