### ISSUE TITLE
i have downloaded tamper monkey and have used the greasy fork link...

### ISSUE THREAD

**Issue by Mrgraham306** [Xmader/musescore-downloader#41]
but when i go to musescore and click on the new buttons that show up, 4 don't do anything, and download midi just says that it is depreciated here is some video of me using it on google chrome and my tamper monkey files, i hope this helps or i can be helped, thank you

![ezgif-3-ef63e7cca8f0](https://user-images.githubusercontent.com/47866184/97226181-058df280-17aa-11eb-96c2-12f82642a85d.gif)
![ezgif-3-0473fcc2fbd0](https://user-images.githubusercontent.com/47866184/97226187-09217980-17aa-11eb-8523-c52ab1e21108.gif)

lso if these are too low rez i can do it again in a higher resolution, i hope someone can help

**Comment by Xmader** [comment]
fixed in `v0.9.8`

**Comment by Mrgraham306** [comment]
xmander, i know that you are busy... but if you... could delete this ticket issue i... would personally feel more... safe.... i dont know how git hub works and im scared something bad might happen to me...

**Comment by Xmader** [comment]
Don't worry, copyright laws will not work that way. Don't be scared by him. The police will do nothing because you just downloaded some files. 

He cannot provide any reasonable statements, so he just tries to frighten anyone he can reach, to make people stop using my script.

**Comment by Mrgraham306** [comment]
forgive me for being scared still but i hope you understand why... i am scared... once again... please take down my issue and don't list it... in the files im sorry... its.. not like i will do anything if you dont but... i... just want out... if there is something you recommend i do i would appreciate the advice... i dont know if this issue can be taken down, if it cant, there is nothing that can be done except making this issue blank
