### ISSUE TITLE
it wont let me download anything;; 

### ISSUE THREAD

**Issue by mqxao** [Xmader/musescore-downloader#45]
instead it just comes up with a dialogue box that goes 
"DEPRECATED! Use 'download MIDI' inside of 'Individual Parts' instead. (This may still work. Click 'OK' to continue) "
and when i do click 'OK' it shows me this:
![image](https://user-images.githubusercontent.com/73699766/97704700-de0e9100-1aed-11eb-942c-8abb9433cd08.png)
:\\ what do i do???

**Comment by Xmader** [comment]
MuseScore updates their site almost everyday, so it won't work if I can't update this script on time.

Just do what the dialogue box says: Go to `Individual Parts`, select `Full score`, and click `download MIDI`.

**Comment by Xmader** [comment]
fixed in `v0.10.2`

**Comment by mqxao** [comment]
thanks !!!
