### ISSUE TITLE
Musescore now detects this script.

### ISSUE THREAD

**Issue by SnekMuffin** [Xmader/musescore-downloader#47]
![download](https://user-images.githubusercontent.com/49637097/98250960-13feba00-1fb3-11eb-9ddd-28d8ba3def4b.png)

Seems we're donezo now.

**Comment by 8bit-coder** [comment]
Yeah, I have this issue too now. RIP.

**Comment by Xmader** [comment]
fixing it

**Comment by Xmader** [comment]
fixed in `v0.11.1`

**Comment by SnekMuffin** [comment]
Oh wow, that was quick. Didn't even hope it was fixable at all. 
Huge thanks, Xmader 👍
