### ISSUE TITLE
Problem downloading MSCZ files, downloads random music sheet instead.

### ISSUE THREAD

**Issue by FelixHappyGamer** [Xmader/musescore-downloader#51]

**Comment by Xmader** [comment]
Which page?

**Comment by BlessingSoftware7** [comment]
![QQ图片20201112165850](https://user-images.githubusercontent.com/51953380/98918265-5cb0f880-2508-11eb-8586-2183a06dae43.png)
https://musescore.com/phoebevu/affections-touching-across-time-inuyasha-ost/piano-tutorial
you can try it,it is doesn t  work.

**Comment by BlessingSoftware7** [comment]
![QQ图片20201112165850](https://user-images.githubusercontent.com/51953380/98918410-8cf89700-2508-11eb-8bec-c6def8a5f96c.png)

**Comment by Xmader** [comment]
https://github.com/Xmader/musescore-downloader/issues/54#issuecomment-726103849

**Comment by Xmader** [comment]
more example: https://musescore.com/oppen_heimer/hana-ni-bourei

**Comment by Xmader** [comment]
fixed
