### ISSUE TITLE
MSCZ Failed, MusicXML stuck on processing

### ISSUE THREAD

**Issue by thegreatuploader** [Xmader/musescore-downloader#52]
Now, I don't know if this is just the WiFi I'm on or another factor. The score I'm trying to download (preferably in MSCZ format) is [https://musescore.com/user/16917646/scores/5490099](url). 

Any help is appreciated.

**Comment by thegreatuploader** [comment]
Update: was the WiFi

**Comment by TheAlienDrew** [comment]
Might want to close the issue then, if it was your wifi.
