### ISSUE TITLE
Downlod .MIDI DONT WORK 

### ISSUE THREAD

**Issue by Keweb** [Xmader/musescore-downloader#53]
hello thks before you create this tools.

yesterday i can download midi extension, but now i cant . tkhs
![Capture](https://user-images.githubusercontent.com/18476093/98890423-e5af3c00-24d6-11eb-8294-68cfc0627fc4.JPG)

**Comment by Xmader** [comment]
fixed in `v0.13.1`

**Comment by Keweb** [comment]
> fixed in `v0.13.1`

thks sir, works now
