### ISSUE TITLE
MIDI download doesn't seems to work or is patched

### ISSUE THREAD

**Issue by Jerry790790** [Xmader/musescore-downloader#54]
![image](https://user-images.githubusercontent.com/63300088/98925880-87ec1580-2511-11eb-9090-e4d90b88a1c8.png)

as shown in the picture the MIDI download button changed to "Processing..." but even if you wait for a couple hours it doesn't download, is this my own problem? I was able to download normally yesterday. I tried reinstalling the script once 10 minutes ago and still don't work. please fix. tq

**Comment by Xmader** [comment]
If the `Download MIDI`, `Download MP3`, or `Download PDF` button does not work, use the corresponding buttons inside `Individual Parts` instead

**Comment by badcodehash** [comment]
What do u mean corresponding buttons? 🤔 Where can I find those? Also I seem to have found a bypass to that with right click view page source. You can find a direct download link there.

**Comment by Xmader** [comment]
> What do u mean corresponding buttons? thinking Where can I find those?

Click `Individual Parts`, and click one of those

![image](https://user-images.githubusercontent.com/16057139/98982313-329e0d00-24ed-11eb-9a64-01ecd136cdcd.png)


> I seem to have found a bypass to that with right click view page source. You can find a direct download link there.

The bypass has been patched.

**Comment by badcodehash** [comment]
What the fuck those musescore guys are scummy. I cant download my midi files for 8 bit music any more D:

All jokes aside, keep up the good work. Ill support you as much as i can with this dmca thing.

**Comment by novxa** [comment]
This works for me, thanks!

**Comment by Jerry790790** [comment]
Thanks for the fix. I was able to download now. tq
