### ISSUE TITLE
It seems musescore has fixed (or broken idk) the plugin.

### ISSUE THREAD

**Issue by AeonCaptain** [Xmader/musescore-downloader#56]
The plugin now no longer functions properly. The extra buttons seem to be missing everywhere, so they've done something to fix(?) it. May have something to do with the ui overhaul (but don't trust me on that, just looks like it is.)

**Comment by Leon-Czajkowski** [comment]
0.15.3 was released a couple of hours ago, try updating it from [here](https://msdl.librescore.org/install.user.js).

**Comment by Leon-Czajkowski** [comment]
> The plugin now no longer functions properly. The extra buttons seem to be missing everywhere, so they've done something to fix(?) it. May have something to do with the ui overhaul (but don't trust me on that, just looks like it is.)

0.15.3 was released a couple of hours ago, try updating it from [here](https://msdl.librescore.org/install.user.js).

**Comment by Lenakeiz** [comment]
Nope 0.15.3 does not seem to work either

**Comment by Leon-Czajkowski** [comment]
The script has been updated to version 0.15.4 two hours ago, I await your comments to see how this new version behaves.

**Comment by Lenakeiz** [comment]
I tried that version and it simply does not download the pdf. No error of any king. Just keep hanging on "Processing..."

**Comment by Leon-Czajkowski** [comment]
> I tried that version and it simply does not download the pdf. No error of any king. Just keep hanging on "Processing..."

Version 0.15.5 was uploaded a couple of hours ago, everything should be in order, I await your confirmation

**Comment by Fackey** [comment]
It doesn't work for me either.

**Comment by Jerry790790** [comment]
> > I tried that version and it simply does not download the pdf. No error of any king. Just keep hanging on "Processing..."
> 
> Version 0.15.5 was uploaded a couple of hours ago, everything should be in order, I await your confirmation

![image](https://user-images.githubusercontent.com/63300088/99187281-ad3a8700-2790-11eb-83f7-de0f3d486f8c.png)
As shown in the picture, I am able to download things normally, even using the normal [DOWNLOAD MIDI] button without going into individual parts.

I don't know about their problem.

**Comment by AeonCaptain** [comment]
It seems the new update has fixed it, as the icons to download the music now appear.
