### ISSUE TITLE
Not working even after 0.15.3 version 

### ISSUE THREAD

**Issue by Al3xX0r** [Xmader/musescore-downloader#58]
Now the buttons appear but only Mscz works and not even midi or individual parts I want Midi and I can't get it.Goddamn you Musescore employees you want money and try to copyright a nice guy go f yourself

**Comment by PeterNjeim** [comment]
Please uninstall any extensions you got from here. Instead, use Tampermonkey and follow the instructions in the new repo, as this repo is no longer updated: https://github.com/LibreScore/dl-librescore

**Comment by PeterNjeim** [comment]
Please uninstall any extensions you got from here. Instead, use Tampermonkey and follow the instructions in the new repo, as this repo is no longer updated: https://github.com/LibreScore/dl-librescore
