### ISSUE TITLE
Individual buttons aren't showing up for me

### ISSUE THREAD

**Issue by Fackey** [Xmader/musescore-downloader#59]
Am I doing something wrong?

**Comment by Xmader** [comment]
Can you post the screenshot?

**Comment by Encode42** [comment]
Fixed in latest release.

**Comment by Fackey** [comment]
Here's a screenshot.

**Comment by Fackey** [comment]
Oops forgot the screen

**Comment by Fackey** [comment]
Apparently I can't upload files (???) so here's an Imgur link
https://imgur.com/a/v8HHj3g

**Comment by Xmader** [comment]
make sure you installed the latest version by https://msdl.librescore.org/install.user.js

**Comment by Fackey** [comment]
Didn't work.
