### ISSUE TITLE
Processing but no download

### ISSUE THREAD

**Issue by Chosaint** [Xmader/musescore-downloader#60]
Seems those pesky folks are at it again lol.

I want to say thank you for putting this out for the community to use. Some of us I know use the .midis from Musescore to play music in Final Fantasy 14. We do it for fun, and the enjoyment of others and enjoyment of music. Thank you for helping us spread joy in these stressful times :)

**Comment by PeterNjeim** [comment]
Can confirm. However I can download .bin files from the mcsz button, and the Music XML and Individual Part buttons open an about:blank page that says "Processing". This may however, be due to me using Firefox for Android. The saddest part is that I discovered this yesterday, and it worked yesterday. Today it stopped working. Perfect timing Ultimate Guitar.

**Comment by Xmader** [comment]
try again with the latest version

**Comment by PeterNjeim** [comment]
> try again with the latest version

Works now, thank you.

**Comment by Chosaint** [comment]
Seems they are keeping up with your progress. Getting the processing error again with 15.8 now.

**Comment by PeterNjeim** [comment]
Can confirm. Same exact characteristics as previously.

**Comment by Xmader** [comment]
fixed in ` v0.15.9`

**Comment by PeterNjeim** [comment]
> fixed in ` v0.15.9`

I don't know how you have the patience to keep updating this several times per day, but you sir are truly the best

**Comment by Chosaint** [comment]
For real man. Thank you. Sorry to spam this issue, but thank you from the bottom of my heart, and everyone else I know that uses it.

**Comment by KnowinglyUnknown** [comment]
I cannot download mp3

**Comment by KnowinglyUnknown** [comment]
I cannot download .mp3 files
It will have a pop up saying "processing..."

**Comment by KnowinglyUnknown** [comment]
10 minutes and nothing happened

**Comment by Xmader** [comment]
If it doesn't work, always try `Individual Parts`

**Comment by KnowinglyUnknown** [comment]
There is no mp3

**Comment by Xmader** [comment]
> There is no mp3

<https://en.wikipedia.org/wiki/FLAC>
<https://en.wikipedia.org/wiki/Ogg_Vorbis>

MP3 is a very old format.   
Those file formats are chosen over MP3 since FLAC can provide better sound quality (lossless), and OGG Vorbis can provide better data compression.   
The most important thing is that MP3 is not fully open-source and royalty-free.

**Comment by KnowinglyUnknown** [comment]
I see, it just confuses me why there is an MP3 option but not used

**Comment by PeterNjeim** [comment]
> I see, it just confuses me why there is an MP3 option but not used

It is being used. If you can't tell or if you haven't taken the time to read the very issue thread you've replied to, MuseScore is currently updating their website to stop this script from working. Normally, all options should work, but it is very difficult to make everything work when the website is changing every few hours.

**Comment by KnowinglyUnknown** [comment]
I see. Wow, they must hate you guys a lot XD

**Comment by PeterNjeim** [comment]
> I see. Wow, they must hate you guys a lot XD

Yup, they even sent a takedown notice. A musescore dev even responded to many complaints in an issue here. It got pretty heated. You can find the threads in talking about easily but I'm too tired to link them

**Comment by Chosaint** [comment]
They really must see this as a threat. If only they got rid of the 20 per day limit, they'd probably get alot more people keeping their pro subs.

**Comment by KnowinglyUnknown** [comment]
Did they just update?

**Comment by Xmader** [comment]
> If only they got rid of the 20 per day limit, they'd probably get alot more people keeping their pro subs.

so everyone can download all MSCZ files, and create every mirror site.
