### ISSUE TITLE
Can't download Midi, Individual parts just keep processing

### ISSUE THREAD

**Issue by IncredibilisMaster** [Xmader/musescore-downloader#62]
Been trying to download for a while, But when I click on "Individual Parts" , A new tab opens and it's stuck on processing, I tried with some other scores, but same result. I'm no tech geek, I even tried restarting the browser with a vpn on and tried again, but it's still stuck on processing. If someone could guide me if I'm doing something wrong, It would be great, Thank you.

**Comment by PeterNjeim** [comment]
Musescore is constantly updating their website to stop this service from functioning. Xmader has been updating this script every few hours to keep up. You just gotta keep checking here for commits, and then update the script in tampermonkey.
