### ISSUE TITLE
Random Music Sheet gets downloaded with Individual Parts

### ISSUE THREAD

**Issue by KenjiRiki** [Xmader/musescore-downloader#63]
I thought it was weird for a second when a song I wanted to play had Violin and Violincellos for the instruments when the Individual Parts are processed, but it turns out every song is like that. At least the ones I tried.

https://musescore.com/user/18022666/scores/6230718
https://musescore.com/user/18022666/scores/6161945

Neither of these gave me the right music sheet for me to use, and instead just gave me a random sheet from god knows where.
![2020-11-20 19_17_02-Funk_Jazz Song no  2 Sheet music for Drum Group, Guitar, Bass, Piano (Mixed Quar](https://user-images.githubusercontent.com/74771237/99794541-4688e500-2b65-11eb-8598-e49ad911cfbb.png)
(Sheet on Musescore site)
![2020-11-20 19_18_02-MuseScore 3_ Funk_Jazz_Song_no_2_](https://user-images.githubusercontent.com/74771237/99794550-4a1c6c00-2b65-11eb-84cb-c7a16f1a54a6.png)
(Sheet on the Musescore program)

**Comment by IncredibilisMaster** [comment]
So wait, it's working fine for you? It's stuck on processing for more than an hour for me

**Comment by KenjiRiki** [comment]
> So wait, it's working fine for you? It's stuck on processing for more than an hour for me
If by fine you mean not being able to use the sheet I got, then yeah. Technically it's "Fine".

Is Musescore screwing with the Music Sheets now?

**Comment by IncredibilisMaster** [comment]
> 
> 
> > So wait, it's working fine for you? It's stuck on processing for more than an hour for me
> 
> If by fine you mean not being able to use the sheet I got, then yeah. Technically it's "Fine".
> Is Musescore screwing with the Music Sheets now?

Idk man, I'm just trying to download a pdf or midi from the website, I click on " Individual Parts " But it's stuck on processing in a new tab.

**Comment by Xmader** [comment]
PDF or MIDI should work now,
and the Individual Parts are fixed.
