### ISSUE TITLE
(Funny) new way MuseScore is blocking us

### ISSUE THREAD

**Issue by RubenVerg** [Xmader/musescore-downloader#64]
They just switched to "Please, disable TamperMonkey to access the website."
lol
Any alternative recommended?

**Comment by JuiceTanWeb** [comment]
Same thing happened to me, but it seems like if you are quick enough, you can still download the score by clicking the button before it disappears.

**Comment by IncredibilisMaster** [comment]
> 
> 
> They just switched to "Please, disable TamperMonkey to access the website."
> lol
> Any alternative recommended?

I used violentmonkey so far no blocks from musescore. But the script doesnt seem to work anymore? Idk, It's stuck on processing after clicking on Individual parts

**Comment by einarmo** [comment]
They just detect the script and refuse to show the page, it is impossible to detect the userscript managers themselves. They could patch the API, but I suspect they haven't done that. Is there some way to "click" the buttons using the console?

**Comment by Xmader** [comment]
> They just switched to "Please, disable TamperMonkey to access the website."
> lol
> Any alternative recommended?

The thing has nothing to do with TamperMonkey.

**Comment by Xmader** [comment]
> They just detect the script and refuse to show the page, it is impossible to detect the userscript managers themselves

It actually detects this script.

**Comment by dbarenholz** [comment]
Hi there! Same issue here using Firefox on Windows (downloaded the latest XPI)

**Comment by Xmader** [comment]
> Hi there! Same issue here using Firefox on Windows (downloaded the latest XPI)

Oh. I forgot to release the XPI of the latest version

**Comment by Xmader** [comment]
> Is there some way to "click" the buttons using the console?

It will expose a global variable which is very easy to be detected

**Comment by RubenVerg** [comment]
Just curious, how does it detect the script itself?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Xmader** [comment]
> Just curious, how does it detect the script itself?

The script loads unused webpack modules on the webpage
