### ISSUE TITLE
How to bypass the tampermonkey block?

### ISSUE THREAD

**Issue by badcodehash** [Xmader/musescore-downloader#66]
So, you see, as of lately this thing seems to just deadass block users with tampermonkey installed. Which to me seems like a huge dick move from the developers. Just today I was tryina download a midi file, but was greeted with the (you guessed it) "please disable tampermonkey to continue to the site" page.

What to do?

Regards, ur #1 simp. :)

**Comment by Xmader** [comment]
just update to v0.15.14

**Comment by badcodehash** [comment]
poggers!!! Also regarding the Daniel dude that came here to bother you, seems like half the stuff he is saying is just useless words and pure demagogy. AFAIK he stopped responding, but it seems that he didnt read your original response to the first sent email.

**Comment by dinnerbird** [comment]
Definitely a reddit moment for sure.

**Comment by badcodehash** [comment]
@xmander yo do u have discord server

**Comment by Xmader** [comment]
#68
