### ISSUE TITLE
Cannot read property 'dataset' of undefined

### ISSUE THREAD

**Issue by ExoticMarbles** [Xmader/musescore-downloader#67]
I took a peek at where the script broke and I got:

> TypeError: Cannot read property 'dataset' of undefined
>     at eval (eval at <anonymous> (userscript.html?name=musescore-downloader.user.js&id=e86f5ca6-31e3-4f09-8443-e78c3ba924c6:NaN), <anonymous>:26327:43)
>     at eval (eval at <anonymous> (userscript.html?name=musescore-downloader.user.js&id=e86f5ca6-31e3-4f09-8443-e78c3ba924c6:NaN), <anonymous>:26334:7)
>     at eval (eval at <anonymous> (userscript.html?name=musescore-downloader.user.js&id=e86f5ca6-31e3-4f09-8443-e78c3ba924c6:NaN), <anonymous>:27109:7)
>     at eval (<anonymous>)
>     at eval (userscript.html?name=musescore-downloader.user.js&id=e86f5ca6-31e3-4f09-8443-e78c3ba924c6:24)
>     at Window.eval (userscript.html?name=musescore-downloader.user.js&id=e86f5ca6-31e3-4f09-8443-e78c3ba924c6:27134)
>     at <anonymous>:3:100
>     at eval (userscript.html?name=musescore-downloader.user.js&id=e86f5ca6-31e3-4f09-8443-e78c3ba924c6:1)
>     at eval (userscript.html?name=musescore-downloader.user.js&id=e86f5ca6-31e3-4f09-8443-e78c3ba924c6:1)
>     at eval (userscript.html?name=musescore-downloader.user.js&id=e86f5ca6-31e3-4f09-8443-e78c3ba924c6:27136)

I hope that code helps you. It seems that the musescore people are really uppity about keeping public domain work to themselves.

**Comment by Xmader** [comment]
fixed
