### ISSUE TITLE
UserScript no longer working on musescore!

### ISSUE THREAD

**Issue by Xerig** [Xmader/musescore-downloader#69]
On Chrome none of the buttons appear on a musescore page when using TamperMonkey. The link to the chrome extension led me to a 404 not found error.

On Firefox a window comes up on a musescore page saying "Please disable TamperMonkey to view this site" even when using the Firefox extension instead of TamperMonkey.

Please could you suggest a way around this issue or provide a fix in the code. I worry the musescore devs are finally getting smart about trying to stop us downloading the content we deserve for free!

Many thanks,
Xerig

**Comment by Xecular** [comment]
I'm having the same issue on version 0.15.15 with Chrome and Tampermonkey. Trying to go to the webpage for a sheet just gives the disable Tampermonkey warning.

**Comment by Xmader** [comment]
fixed in `v0.15.16`
