### ISSUE TITLE
Download buttons no longer appear [0.15.16]

### ISSUE THREAD

**Issue by Xecular** [Xmader/musescore-downloader#70]
Using Tampermonkey and script version 0.15.16

Browsing the webpages for sheets does not show any download buttons except for the default one which tells you to buy a subscription.
![image](https://user-images.githubusercontent.com/32306390/99887755-0e40df80-2c15-11eb-87fb-6515bbed5c4c.png)

**Comment by PeterNjeim** [comment]
Works for me. Must be something on your end

**Comment by Xecular** [comment]
> Works for me. Must be something on your end, maybe it's that specific song?

Seems like it was a cookie issue on my end, after clearing my cookies and cache it appears to be working correctly
