### ISSUE TITLE
Only downloads half of the sheet

### ISSUE THREAD

**Issue by gonzalovozpito** [Xmader/musescore-downloader#71]
I found a problem while downloading some sheets, and there is a point where the music notes stop and there are only silence notes:
![Captura](https://user-images.githubusercontent.com/37085829/99904474-5ae6f200-2ccb-11eb-978a-e3d28d046a81.PNG)

Here I send the PDF of how it should be:
[sparkle.pdf](https://github.com/Xmader/musescore-downloader/files/5579517/sparkle.pdf)

**Comment by gonzalovozpito** [comment]
Here I leave the sheet link: https://musescore.com/user/3443166/scores/5910045

**Comment by Xmader** [comment]
fixed
