### ISSUE TITLE
doesnt download anything, just stayed on "processing...". 

### ISSUE THREAD

**Issue by mqxao** [Xmader/musescore-downloader#75]
it does the same in incognito, and after i've cleared cookies and cache. have removed and reinstalled code but still does the same. :[
[some things edited out bcoz privacyyy]
was trying to dl this score >> https://musescore.com/user/35272338/scores/6460635
![image](https://user-images.githubusercontent.com/73699766/100040246-d8cd0980-2e41-11eb-867b-3e332c06c46e.png)

**Comment by Xmader** [comment]
There is a [dedicated channel on Discord](https://discord.com/channels/774491656643674122/780520933101535232) to post those missing scores

**Comment by Xmader** [comment]
added https://ipfs.io/ipfs/QmZfSPmw9Pp1W3giGbwDNxgyujaVmoe7bt4ZP488BNErhn
