### ISSUE TITLE
"Disable Tampermonkey to access this website" ???

### ISSUE THREAD

**Issue by FelixHappyGamer** [Xmader/musescore-downloader#77]
![imagen](https://user-images.githubusercontent.com/71792978/100125863-2d3dac80-2e75-11eb-9f22-23c75d89706c.png)

**Comment by NoctIsFree** [comment]
I just got this same issue as well. I'm looking into how sites detect the extension and if there's any way to stop it. Musescore is getting way too greedy...

**Comment by NoctIsFree** [comment]
Until a good fix comes out, I recommend using snipping tool or greenshot on each page, then save all them all to a folder with ascending  names. You can select all and use print to pdf and you have something very similar to the pdf downloader, although not as convenient.

**Comment by miclol** [comment]
Have you guys updated to the latest version yet? ([Latest Version](https://msdl.librescore.org/install.user.js))

**Comment by NoctIsFree** [comment]
Miclol, that got it, thanks! Although if they do continue seeking to block music behind a paywall, the method I mentioned earlier does work. I imagine, they'd even block the ability to access full scores soon.

**Comment by NoctIsFree** [comment]
Nevermind, it only endlessly says processing now. Looking at the console, it appears the script is attempting to access a nonexistent site. Maybe musescore changed how they load files?

**Comment by miclol** [comment]
What's the musescore link and what are you trying to download?

**Comment by NoctIsFree** [comment]
https://musescore.com/user/206309/scores/194437

**Comment by NoctIsFree** [comment]
pdf form

**Comment by NoctIsFree** [comment]
mscz is the only option currently working on that score for me. Sorry for flooding the comments

**Comment by miclol** [comment]
Hmm... I guess we need to wait for the next update then I guess...  ¯\_(ツ)_/¯

**Comment by msteknoadam** [comment]
Yeah same here :/ This looks to be the issue, I don't get why it gets 500 error tho since I don't know the API and can't access documentation of the given address.
![opera_EFAbYXmA36](https://user-images.githubusercontent.com/40995274/100141232-23cb3900-2ea3-11eb-8313-b0f4200df5cd.png)

**Comment by NoctIsFree** [comment]
In the meantime, try using greenshot's fixed capture region or use the method posted in the discord (pinned in issues)

**Comment by miclol** [comment]
Woo! New update! Hopefully the probs fixed... ([Latest Version](https://msdl.librescore.org/install.user.js))
