### ISSUE TITLE
Not seeing download buttons

### ISSUE THREAD

**Issue by RuralAnemone** [Xmader/musescore-downloader#78]
Ever since a few updates ago I haven't been seeing the download buttons
Attached is a recording of my despair
[aaaaaaaaaaaaaaaaaaaaaaaa.zip](https://github.com/Xmader/musescore-downloader/files/5599243/aaaaaaaaaaaaaaaaaaaaaaaa.zip)

**Comment by Xmader** [comment]
fixed in `v0.17.0`

**Comment by RuralAnemone** [comment]
k thanks -- also musescore blocked tampermonkey...?

**Comment by RuralAnemone** [comment]
(I'm constantly updating this btw)

**Comment by Xmader** [comment]
fixed in `v0.19.2`

By the way, there is always an alternative method, see [CLI Usage](https://github.com/Xmader/musescore-downloader#cli-usage)

**Comment by RuralAnemone** [comment]
Thanks
