### ISSUE TITLE
Disable Tampermonkey

### ISSUE THREAD

**Issue by l4l4louislol** [Xmader/musescore-downloader#79]
They put extension detection i think, we might need other trigger to open it instead of trigger it on enter website

**Comment by Xmader** [comment]
fixed in `v0.17.0`

**Comment by North-West-Wind** [comment]
I don't think that fixed it. I'm running on the latest release (4 hours ago) and they still tell me to disable tampermonkey.

**Comment by Xmader** [comment]
> I don't think that fixed it. I'm running on the latest release (4 hours ago) and they still tell me to disable tampermonkey.

fixed again
