### ISSUE TITLE
Have got latest most updated version, tried everything, yet this insists on appearing

### ISSUE THREAD

**Issue by FelixHappyGamer** [Xmader/musescore-downloader#82]
![imagen](https://user-images.githubusercontent.com/71792978/100466090-425e4980-30c8-11eb-8e22-d6a40eb729bb.png)

**Comment by novxa** [comment]
This is really recent, looks like they gave up on their cease and desist letter :D

**Comment by Xmader** [comment]
fixed in `v0.19.2`

**Comment by Xmader** [comment]
By the way, there is always an alternative method, see [CLI Usage](https://github.com/Xmader/musescore-downloader#cli-usage)
