### ISSUE TITLE
Score not in Dataset

### ISSUE THREAD

**Issue by Xerig** [Xmader/musescore-downloader#83]
Does this program only work with older scores or more recent ones as well because I attempted to download a recent score (a week old) and using tampermonkey "Download Failed" appeared and using `npx msdl` it returned the error `score not in dataset`

Is this to do with the date published or did I just get unlucky as it has worked for other scores I attempted to download.

**Comment by Xmader** [comment]
Please report the URL to [Discord](https://discord.com/channels/774491656643674122/780520933101535232)
