### ISSUE TITLE
No channels on Discord, even after 10 minutes waiting

### ISSUE THREAD

**Issue by Pilzinsel64** [Xmader/musescore-downloader#86]
I joined the Discord server to ask about a problem (can't download any file format of [this](https://musescore.com/giuliom/life-for-my-mother/)) but even after 10 minutes there are only the information channels. Is that normal? How to get the other channels?
![grafik](https://user-images.githubusercontent.com/23138465/100546677-e5e36180-3262-11eb-943a-a0f2401da113.png)

**Comment by Jabster28** [comment]
Did you get a DM from a captcha bot?

**Comment by Pilzinsel64** [comment]
No I didn't. But right now (after about 35h) I can see all other channels. Maybe someone did it manually. Thanks!
