### ISSUE TITLE
score not in dataset

### ISSUE THREAD

**Issue by lincoln123987** [Xmader/musescore-downloader#88]
i can download the old midi files with cmd, but the latest midi files, it shows score not in dataset, pls, fix it brother...
![score](https://user-images.githubusercontent.com/73014587/100611478-66739200-3337-11eb-886b-b424ba89c2f5.PNG)

**Comment by Xmader** [comment]
Please report the URL to [Discord](https://discord.com/channels/774491656643674122/780520933101535232)
