### ISSUE TITLE
I can't use

### ISSUE THREAD

**Issue by rk0ga** [Xmader/musescore-downloader#91]
Please, I'm trying to use this, but I couldn't. Can anyone help me, maybe I didn't configured correctly, 'cause I don't know how to use scripts and etc. Thanks

**Comment by VerMishelb** [comment]
Same for me. 20.0 with psycho-neon's fix code worked fine but 20.1 is not showing any buttons anywhere.

**Comment by Xmader** [comment]
fixed in `v0.20.2`
