### ISSUE TITLE
Disable Tampermonkey to access the website

### ISSUE THREAD

**Issue by fadfdsaadfd** [Xmader/musescore-downloader#93]
20.3 .... Disable Tampermonkey to access the website...............

**Comment by joscabmar** [comment]
I tried with Greasemonkey and I could get around the blocker for Tampermonkey. But I am still having issues:

<img width="1680" alt="Screen Shot 2020-12-01 at 19 40 29" src="https://user-images.githubusercontent.com/6691911/100782815-41e9e980-340d-11eb-8be9-e490ef64c6b4.png">

**Comment by Xmader** [comment]
> I tried with Greasemonkey and I could get around the blocker for Tampermonkey. But I am still having issues:
> 
> <img alt="Screen Shot 2020-12-01 at 19 40 29" width="1680" src="https://user-images.githubusercontent.com/6691911/100782815-41e9e980-340d-11eb-8be9-e490ef64c6b4.png">

fixed in `v0.20.5`
