### ISSUE TITLE
Score not in dataset

### ISSUE THREAD

**Issue by KnowinglyUnknown** [Xmader/musescore-downloader#96]
I cannot download this score, any clues why.
https://musescore.com/user/12456681/scores/6482670
![image](https://user-images.githubusercontent.com/64538745/100979048-3833c380-357e-11eb-94d2-eb1dde7a1a19.png)

**Comment by Xmader** [comment]
Please report the URL to [Discord](https://discord.com/channels/774491656643674122/780520933101535232)
