### ISSUE TITLE
Unable to download any sheet music from Musescore. Thanks!

### ISSUE THREAD

**Issue by SMLibrary** [Xmader/musescore-downloader#97]

**Comment by SMLibrary** [comment]
Unable to download any sheet music from Musescore. Thanks!

**Comment by Jockeystrap** [comment]
I had the same problem as you but I played around with Tampermonkey Beta and figured out a simple solution to make it work.
Disable Tampermonkey before accessing the page with the sheet music you want, then enable Tampermonkey and CLICK REFRESH.
Download your file then disable Tampermonkey and CLICK REFRESH before leaving page to get another sheet, repeat the same steps for each file.
Works for me so far.... good luck.

**Comment by SMLibrary** [comment]
Hi,

Many thanks for your comments.

In fact, I was going to try it and disabled the Greasemonkey Musescore downloader..... and it worked anyway! Strange! So, now it’s working with the disabled script, but I will keep in mind your advice.

Take care.

Jordi

De: Jockeystrap<mailto:notifications@github.com>
Enviat: divendres, 4 de desembre de 2020 5:04
Per a: Xmader/musescore-downloader<mailto:musescore-downloader@noreply.github.com>
A/c: SMLibrary<mailto:jordipa@hotmail.com>; Author<mailto:author@noreply.github.com>
Tema: Re: [Xmader/musescore-downloader] Unable to download any sheet music from Musescore. Thanks! (#97)


I had the same problem as you but I played around with Tampermonkey Beta and figured out a simple solution to make it work.
Disable Tampermonkey before accessing the page with the sheet music you want, then enable Tampermonkey and CLICK REFRESH.
Download your file then disable Tampermonkey and CLICK REFRESH before leaving page to get another sheet, repeat the same steps for each file.
Works for me so far.... good luck.

**Comment by sjkim04** [comment]
Please close the issue if your problem is solved.

**Comment by SMLibrary** [comment]
It seems to work sometimes, sometimes not.
